<?php

namespace App\Support\Cuestionarios;

/**
 * Banco de preguntas del examen de Juez ATA (BEKHO Chile), transcrito del
 * "Manual del Juez" (reglamento ATA 2025-2026). Es la fuente única para sembrar
 * los cuestionarios del módulo de evaluaciones; el módulo en sí es genérico y
 * cualquier examinador puede crear otros bancos desde la interfaz.
 *
 * Cada nivel devuelve una lista de preguntas:
 *   ['q' => enunciado, 'options' => [...], 'correct' => índice correcto,
 *    'why' => explicación, 'flag' => bool? (pregunta ambigua)]
 */
class BancoJuez
{
    /**
     * Cuestionarios a sembrar: metadatos + preguntas de cada nivel.
     *
     * @return list<array{titulo: string, area: string, descripcion: string, preguntas: list<array{q: string, options: list<string>, correct: int, why: string, flag?: bool}>}>
     */
    public static function cuestionarios(): array
    {
        $q = self::preguntas();

        return [
            ['titulo' => 'Examen de Juez ATA — Nivel 1', 'area' => 'Arbitraje', 'descripcion' => 'Certificación de Juez Nivel 1 (galón azul): fórmula y sparring, roles de los jueces y escala de puntajes.', 'preguntas' => $q[1]],
            ['titulo' => 'Examen de Juez ATA — Nivel 2', 'area' => 'Arbitraje', 'descripcion' => 'Certificación de Juez Nivel 2 (galón rojo): Central en color, armas, procedimientos de ring y sparring.', 'preguntas' => $q[2]],
            ['titulo' => 'Examen de Juez ATA — Nivel 3', 'area' => 'Arbitraje', 'descripcion' => 'Certificación de Juez Nivel 3 (galón negro): arbitraje en cinturones negros, clasificaciones y resolución de conflictos.', 'preguntas' => $q[3]],
            ['titulo' => 'Repaso de puntuación y combate', 'area' => 'Arbitraje', 'descripcion' => 'Ejercicios de puntuación de fórmula, sparring y combat weapons: zonas, señales y advertencias.', 'preguntas' => $q[4]],
        ];
    }

    /**
     * @return array<int, list<array{q: string, options: list<string>, correct: int, why: string, flag?: bool}>>
     */
    private static function preguntas(): array
    {
        return [
            1 => [
                ['q' => '¿Cuál es el objetivo de la evaluación en la competencia de fórmulas?', 'options' => ['Evaluar la técnica universal considerando diferencias por escuela/región.', 'Evaluar habilidad en la ejecución de técnicas y movimientos.', 'Evaluar coordinación, concentración y fuerza.', 'Todas las anteriores.', 'B y C.'], 'correct' => 3, 'why' => 'Contempla los tres aspectos: técnica universal, habilidad de ejecución y atributos como coordinación y fuerza.'],
                ['q' => 'Para la evaluación de fórmula son necesarios:', 'options' => ['2 Jueces y un planillero.', '3 Jueces y cronómetro.', '3 Jueces y un planillero.', '4 Jueces y un planillero.', 'Sólo 2 Jueces.'], 'correct' => 2, 'why' => 'Fórmula: 3 jueces y un planillero. No lleva cronómetro (sin límite de tiempo en campeón).'],
                ['q' => '¿Qué característica NO tiene que ver con el Juez Central?', 'options' => ['Tiene autoridad sobre TODOS los competidores de su categoría.', 'Controlar que se cumplan las reglas.', 'Puede descalificar a un competidor por sí solo.', 'Hacer llegar los resultados a la mesa central.', 'A y D.'], 'correct' => 2, 'why' => 'Ningún juez descalifica por sí solo ni anula a otro: todos los votos pesan igual. Los problemas serios van al RTTL.'],
                ['q' => 'Indique qué evaluación NO está correcta:', 'options' => ['9.9 el mejor del grupo.', '9.8–9.6 mejor que el promedio.', '9.5 el promedio.', '9.4–9.1 debajo del promedio.', '9.0 fórmula incompleta, la colocan los tres jueces.'], 'correct' => 4, 'why' => 'Falsa: en fórmula incompleta SOLO el Central otorga el 9.0/0; los de esquina evalúan normal.'],
                ['q' => 'Indique la alternativa que está correcta:', 'options' => ['Si son 3 competidores, salen los tres a presentar y luego se colocan las notas según los criterios.', 'En Creative Weapons se permite lanzar el arma.', 'En Xtreme fórmula se descuenta 1 pt de los tres jueces si pasa de 2 min.', 'En armas tradicionales se descuenta 1 pt si rompe y consigue otra en 30 seg.', 'Con 3 en fórmula tradicional, el 2do lugar siempre obtiene 8-8-8.'], 'correct' => 0, 'flag' => true, 'why' => 'Correcta la (a). En Creative no se lanza el arma; el arma rota no se penaliza; en Xtreme la sanción es 0 del central. Ojo: la opción (e) también puede darse por válida en el sistema antiguo.'],
                ['q' => 'Fórmula incompleta — puntaje de los Jueces de esquina:', 'options' => ['9.0', '9.5', '9.0 ó 9.1', '9.1 a 9.9', '9.0 a 9.5'], 'correct' => 3, 'why' => 'Los de esquina puntúan normal (9.1–9.9). El 9.0/0 lo pone solo el Central.'],
                ['q' => '¿Cuántas oportunidades para hacer la fórmula hay?', 'options' => ['1 vez para todos los grados.', '2 para Cinturones Negros con autorización.', '1 leadership y 1 Cinturón Negro.', '1 Negro y 2 Color.', '1 Negro (excepto infantil) y 2 Color.'], 'correct' => 0, 'why' => 'Una sola oportunidad para todos. La fórmula no se repite en ninguna categoría.'],
                ['q' => 'Para la evaluación de Sparring debe haber como mínimo:', 'options' => ['2 Jueces, planillero y cronómetro.', 'Un cronómetro, 3 Jueces y un planillero.', 'Un Juez y un planillero.', 'Sólo 3 Jueces.', 'Un central, un esquina, dos asistentes.'], 'correct' => 1, 'why' => 'Sparring: cronómetro, 3 jueces y planillero (a diferencia de fórmula, que no usa cronómetro).'],
                ['q' => "¿Qué se entiende por 'Victoria Súbita'?", 'options' => ['Ganar dentro del tiempo reglamentario.', 'El competidor se lesiona y no puede continuar.', "Ganar en tiempo extra 'a criterio' de los jueces.", 'Ganar después de un empate, en un tiempo extra.', 'B y C.'], 'correct' => 3, 'why' => 'Tras un empate, en tiempo extra el primer punto gana, sin límite de tiempo.'],
                ['q' => '¿En qué momento los Jueces de esquina dan sus puntajes?', 'options' => ['En cualquier momento.', 'Cuando el combate está detenido y el Central lo pide.', 'Cuando ven puntos y detienen el combate.', 'Cuando ven mala intención.', 'En cualquier momento tras llamar a punto.'], 'correct' => 1, 'why' => 'Votan simultáneamente cuando el Central detiene el combate y pide la verificación.'],
            ],
            2 => [
                ['q' => 'Un Juez Nivel 2 está certificado para cubrir ¿cuál posición?', 'options' => ['Central en Cinturones de Color.', 'Esquina en Cinturones Negros.', 'Esquina en Cinturones de Color.', 'Todas.'], 'correct' => 3, 'why' => 'Nivel 2: esquina o central en color, y esquina en negro hasta su rango. Todas aplican.'],
                ['q' => 'Las responsabilidades del Juez Central son:', 'options' => ['Velar por que cada competidor siga las reglas.', 'Controlar su ring durante la competencia.', 'Controlar que los resultados se traspasen a la planilla.', 'Todas las anteriores.'], 'correct' => 3, 'why' => 'El Central cumple las tres funciones.'],
                ['q' => 'Una vez recibida la categoría asignada, el Juez Central debe:', 'options' => ['Revisar que todos sean del mismo grado y rango de edad.', 'Dejar la categoría haciendo calentamiento.', 'Supervisar que estén las planillas necesarias.', 'A y C.'], 'correct' => 3, 'why' => 'Confirma grado/edad y supervisa planillas. NO debe calentar físicamente a los competidores.'],
                ['q' => '¿Cuál es el orden de las competencias?', 'options' => ['Fórmula, Armas, Sparring.', 'Fórmula, Armas, Sparring, Combat Weapons.', 'Xtreme, Fórmula, Sparring, Armas, CW.', 'Fórmula, Armas, Combat Weapons, Sparring, Creative, Xtreme.'], 'correct' => 3, 'why' => 'Orden oficial: forma → armas → combat weapons → sparring → creative → xtreme.'],
                ['q' => 'Si un competidor llega tarde a su pista asignada, lo correcto es:', 'options' => ['Entra a fórmula mientras no se presente el último competidor.', 'Entra a combat weapons mientras no corra el 2do encuentro de 1ra ronda.', 'Entra a fórmula mientras no se llame al 1er competidor de armas.', 'Si quedan 3 por presentar en fórmula, se acepta y presenta en último lugar.'], 'correct' => 3, 'why' => 'Si la modalidad no se ha cerrado, se acepta e ingresa para competir de último, sin tiempo extra.'],
                ['q' => 'El Juez Central en fórmulas evaluará:', 'options' => ['Patadas y posiciones.', 'Básicos y Defensas.', 'Memoria y actitud.', 'Todas.'], 'correct' => 3, 'why' => 'El Central evalúa la presentación general, que incluye todos los criterios.'],
                ['q' => 'Un Cinturón de Color, ¿cuántas veces puede repetir su fórmula?', 'options' => ['Dos veces.', 'Cuantas necesite si es Tiny Tiger.', 'Una vez.', 'Ninguna.'], 'correct' => 3, 'why' => 'Se presenta una sola vez: no se repite (cero repeticiones) en ninguna categoría.'],
                ['q' => 'Indique la alternativa que está correcta:', 'options' => ['Si son 3 competidores, salen los tres a presentar y luego se colocan las notas.', 'En Creative se permite lanzar el arma.', 'En Xtreme se descuenta 1 pt si pasa de 2 min.', 'En armas se descuenta 1 pt si rompe y consigue otra en 30 seg.', 'Con 3 en fórmula, el 2do siempre obtiene 8-8-8.'], 'correct' => 0, 'flag' => true, 'why' => 'Correcta la (a). La (e) puede ser válida en el sistema antiguo.'],
                ['q' => 'Si un competidor se salta un paso en su fórmula, los Jueces de Esquina deben:', 'options' => ['Ignorar el hecho, bajando el puntaje máximo.', 'Advertir y hacer que la presente de nuevo.', 'Bajar el puntaje.', 'No hacer nada.'], 'correct' => 3, 'why' => 'Los de esquina solo juzgan las técnicas mostradas; descontar por omisiones es tarea del Central.'],
                ['q' => 'Una fórmula incompleta se define como:', 'options' => ['Fórmula hecha sin gritos.', 'Olvidar o saltarse 2 movimientos.', 'No terminar donde comenzó.', 'Omitir al menos 4 movimientos consecutivos.'], 'correct' => 3, 'why' => 'Incompleta = omitir 4+ movimientos consecutivos o detenerse y no continuar.'],
                ['q' => 'Si un competidor sale del perímetro de competencia (fórmula):', 'options' => ['El Central descuenta puntos.', 'Los de esquina descuentan puntos.', 'No se descuentan puntos.', 'Dos salidas y el Central descuenta.'], 'correct' => 2, 'why' => 'No hay restricción de límites en fórmula: no se penaliza salir del área.'],
                ['q' => 'El Central pide puntajes en una fórmula no muy buena y los de esquina dan notas muy altas. ¿Qué hace?', 'options' => ['Manifestar acuerdo/desacuerdo verbal con los puntajes.', 'Asegurar que el planillero escriba los puntajes correctos.', 'Escribir en Observaciones su desacuerdo con los de esquina.', 'Ninguna de las anteriores.'], 'correct' => 3, 'flag' => true, 'why' => 'Cada juez puntúa su área de forma independiente; el Central no interfiere en los puntajes de esquina.'],
                ['q' => 'Terminada la competencia de fórmulas, el Juez Central debe:', 'options' => ['Confirmar que todos se hayan presentado.', 'Verificar la puntuación en la planilla.', 'Verificar empates.', 'Todas.'], 'correct' => 3, 'why' => 'Confirma presentaciones, verifica puntajes y revisa empates.'],
                ['q' => '¿Cuál de las siguientes acciones está permitida?', 'options' => ['Enrollar las mangas del dobok a la altura del codo.', 'Las puntas del cinturón pueden guardarse siguiendo la línea del mismo.', 'Enrollar las mangas a la altura del antebrazo.', 'Ninguna.'], 'correct' => 1, 'flag' => true, 'why' => 'Las puntas del cinturón pueden acomodarse siguiendo su línea.'],
                ['q' => 'Si un competidor en Xtreme Formula se pasa del tiempo reglamentario:', 'options' => ['El puntaje debe ser rebajado.', 'El central otorga 0 y los de esquina puntúan normal.', 'No ajustar por tiempo sino por movimientos.', 'No podrá recibir puntaje por pasarse del tiempo.'], 'correct' => 1, 'why' => 'Hoy no hay descalificación por tiempo: el Central da 0 y los de esquina puntúan normal.'],
                ['q' => 'En la competencia de Tigers en Chile, indique la alternativa INCORRECTA:', 'options' => ['En fórmula los tres jueces muestran pulgares arriba y el central felicita.', 'En armas tradicional puede hacer una fórmula libre de 30 seg.', 'En Sparring se marca alternadamente rojo/blanco para que empaten y ambos ganan.', 'En Combat Weapons arbitran normal pero el marcador queda en cero y ambos ganan.', 'Se le da una medalla por fórmula-Sparring y otra por cada competencia extra.'], 'correct' => 2, 'flag' => true, 'why' => 'Falsa: en Tigers el sparring NO se puntúa; el juez comenta lo positivo. Detalles específicos de Chile.'],
                ['q' => 'La principal consideración al evaluar armas debe ser:', 'options' => ['Presentación general del material y manejo por ambos lados.', 'Calidad de las patadas.', 'Tiempo y fluidez de movimientos del arma.', 'A y C.'], 'correct' => 3, 'why' => 'Se evalúa la presentación/manejo y el tiempo-fluidez (control del arma es el criterio rector).'],
                ['q' => 'Si el arma se cae:', 'options' => ['Se descuenta 1 pt por cada caída.', 'Se detiene y se comienza de nuevo.', 'Solo el Central baja el puntaje por mala precisión.', 'Se evalúa con 9.1 en cinturones negros.'], 'correct' => 0, 'why' => 'Todos los jueces descuentan 1 punto por cada caída del arma en armas tradicionales.'],
                ['q' => 'El rol principal del Juez Central durante la competencia es:', 'options' => ['Determinar un ganador.', 'Cuidar la integridad de todos los competidores.', 'Determinar puntos claros.', 'Dejar contento al público.'], 'correct' => 1, 'why' => 'La seguridad/integridad de los competidores es la prioridad del Central.'],
                ['q' => 'Protectores para los competidores:', 'options' => ['Obligatorios para Cinturones Negros.', 'Opcionales para Cinturón de Color.', 'Obligatorios para todos los Cinturones.', 'A criterio del Juez Central.'], 'correct' => 2, 'why' => 'El equipo de seguridad es obligatorio para todos en sparring y combat weapons.'],
                ['q' => 'Antes de comenzar la categoría de sparring, el Central debe:', 'options' => ['Verificar que todos tengan protectores.', 'Explicar las reglas generales de sparring.', 'Explicar qué esperan los jueces.', 'Todas.'], 'correct' => 3, 'why' => 'Verifica equipo, explica reglas y expectativas antes de empezar.'],
                ['q' => 'Un Juez puede cambiar el color de la bandera en el caso de:', 'options' => ['Que los otros jueces hayan indicado al otro competidor.', 'Apunta al rojo con la bandera blanca.', 'Cuando el público pifia.', 'Ninguna.'], 'correct' => 1, 'why' => 'Si apunta al competidor correcto pero levanta el color equivocado, puede corregir el color.'],
                ['q' => 'Si un Juez escucha un punto pero no lo ve, ¿qué marca?', 'options' => ['1 punto.', 'No punto.', 'Advertencia.', 'No visto.'], 'correct' => 3, 'why' => "Debe ver, no solo oír. Si no lo vio, marca 'No visto' y sale de la votación."],
                ['q' => 'Si un competidor muestra actitudes poco deportivas, ¿qué acción se toma?', 'options' => ['Sancionarlo con una advertencia.', 'Ignorarlo.', 'Hacer flexiones.', 'Descalificarlo sin advertencia previa.'], 'correct' => 0, 'why' => 'Advertencia por conducta antideportiva (a criterio del Central; puede escalar a punto o descalificación).'],
                ['q' => 'El Central llama a punto y se marcan: 2 rojos, 3 rojos y 1 rojo. ¿Qué puntuación se entrega?', 'options' => ['Cero puntos.', '3 puntos rojos.', '1 punto rojo.', '2 puntos rojos.'], 'correct' => 3, 'why' => 'Mayoría a rojo. La puntuación común más alta apoyada por la mayoría (2 de 3 dieron 2+) es 2.'],
            ],
            3 => [
                ['q' => 'Un Juez Nivel 3 está certificado para cubrir ¿cuál posición?', 'options' => ['Central en Cinturones de Color.', 'Esquina en Cinturones Negros.', 'Central en Cinturones Negros.', 'Todas.'], 'correct' => 3, 'why' => 'Nivel 3: esquina/central en color, esquina en negro hasta su rango y central en negro hasta un rango menor al suyo.'],
                ['q' => 'Las responsabilidades del Juez Central son:', 'options' => ['Velar por las reglas.', 'Controlar su ring.', 'Controlar el traspaso de resultados a la planilla.', 'Todas las anteriores.'], 'correct' => 3, 'why' => 'Cumple las tres funciones.'],
                ['q' => 'Una vez recibida la categoría, el Central debe:', 'options' => ['Revisar mismo grado y rango de edad.', 'Dejar la categoría calentando.', 'Supervisar planillas necesarias.', 'A y C.'], 'correct' => 3, 'why' => 'Confirma grado/edad y supervisa planillas; no calienta competidores.'],
                ['q' => '¿Cuál es el orden de las competencias?', 'options' => ['Fórmula, Armas, Sparring, CW, Creative, Xtreme.', 'Armas, Fórmula, Sparring.', 'Xtreme, Fórmula, Sparring, Armas.', 'Fórmula, Armas, CW, Sparring, Creative, Xtreme.'], 'correct' => 3, 'why' => 'Forma → armas → combat weapons → sparring → creative → xtreme.'],
                ['q' => 'Mientras la planilla se completa, ¿qué debe hacer el Central?', 'options' => ['Esperar a que se termine la planilla.', 'Presentar a los jueces y comenzar la categoría.', 'Explicar las reglas generales a los competidores.', 'B y C.'], 'correct' => 3, 'why' => 'Aprovecha para presentar jueces, explicar reglas y comenzar.'],
                ['q' => 'Si un menor se lesiona (lesión media), para continuar el Central debe:', 'options' => ['Esperar autorización de los paramédicos.', 'Esperar autorización del instructor (si no están los padres).', 'Ambas en el mismo orden.', 'Ambas en cualquier orden.'], 'correct' => 2, 'why' => 'Primero decide el equipo médico; luego el instructor/padres si están presentes (en ese orden).'],
                ['q' => 'Si un Juez Nivel 3 no está de acuerdo con una regla, puede:', 'options' => ['Alterarla.', 'Modificarla consultando a los de esquina.', 'Pedir autorización al Jefe de Torneos para modificarla.', 'Ninguna.'], 'correct' => 3, 'why' => 'Ningún juez puede alterar o modificar las reglas ATA; solo consultar al RTTL por interpretación.'],
                ['q' => 'Durante el torneo, ¿qué calzado debe usar un juez?', 'options' => ['Sandalias.', 'Deportivas cualquiera.', 'Deportivas blancas.'], 'correct' => 2, 'why' => 'Descalzo o zapatillas predominantemente blancas (o negras). Las sandalias ATA no sirven para jueces.'],
                ['q' => 'El Juez Central en una competencia evaluará:', 'options' => ['Patadas y posiciones.', 'Básicos y defensas.', 'Actitud y memoria.', 'Todas.'], 'correct' => 3, 'why' => 'El Central evalúa la presentación general (todos los criterios).'],
                ['q' => 'Un Cinturón de Color, ¿cuántas veces puede repetir su fórmula?', 'options' => ['Dos veces.', 'Cuantas necesite si es tiny tiger.', 'Una vez.', 'Ninguna.'], 'correct' => 3, 'why' => 'Una sola presentación: no se repite en ninguna categoría.'],
                ['q' => '¿Cuántos puntos por salir 2do lugar en un torneo panamericano?', 'options' => ['5', '8', '10', '12'], 'correct' => 2, 'why' => 'El Panamericano es Clase AA (Nacional): 2do lugar = 10 puntos.'],
                ['q' => 'Si un competidor llega tarde a su pista, lo correcto es:', 'options' => ['Entra a fórmula mientras no se presente el último.', 'Entra a CW mientras no corra el 2do encuentro de 1ra ronda.', 'Entra a fórmula mientras no se llame al 1er competidor de armas.', 'Si quedan 3 por presentar en fórmula, se acepta y presenta de último.'], 'correct' => 3, 'why' => 'Si la modalidad no se cerró, se acepta y compite de último sin tiempo extra.'],
                ['q' => 'Si se salta un paso en su fórmula, los Jueces de Esquina deben:', 'options' => ['Ignorar bajando el puntaje máximo.', 'Advertir y repetir.', 'Bajar el puntaje.', 'No hacer nada.'], 'correct' => 3, 'why' => 'Los de esquina solo juzgan técnicas mostradas; el descuento por omisión es del Central.'],
                ['q' => 'Una fórmula incompleta se define como:', 'options' => ['Fórmula sin gritos.', 'Olvidar o saltarse 2 movimientos.', 'No terminar donde comenzó.', 'Omitir al menos 4 movimientos consecutivos.'], 'correct' => 3, 'why' => 'Omitir 4+ movimientos consecutivos o detenerse y no continuar.'],
                ['q' => 'Si un competidor sale del perímetro (fórmula):', 'options' => ['El Central descuenta.', 'Los de esquina descuentan.', 'No se descuentan puntos.', 'Dos salidas y el Central descuenta.'], 'correct' => 2, 'why' => 'No hay restricción de límites en fórmula.'],
                ['q' => 'Terminada la competencia de fórmulas, el Central debe:', 'options' => ['Confirmar que todos se presentaron.', 'Verificar la puntuación.', 'Verificar empates.', 'Todas.'], 'correct' => 3, 'why' => 'Confirma presentaciones, verifica puntajes y empates.'],
                ['q' => 'Si un competidor ajusta su posición para evitar un obstáculo, los jueces deben:', 'options' => ['Ignorar el hecho.', 'Reducir el puntaje.', 'Dejar que repita.', 'Incrementar el puntaje por manejarlo.'], 'correct' => 0, 'why' => 'No se penaliza ajustar la posición para evitar obstáculos o límites.'],
                ['q' => 'Si hay 2 o 3 competidores en una categoría, el procedimiento es:', 'options' => ['Sacar uno a la vez y dar puntaje inmediato.', 'Sacar a los competidores y luego indicar al mejor entre ellos.', 'Sacar uno por uno y luego dar el puntaje.', 'Ninguna.'], 'correct' => 1, 'why' => 'Con 2-3, no se dan notas: cada juez apunta su elección (1°=9, 2°=8, 3°=7).'],
                ['q' => 'Cuando hay empate en fórmula, el Central instruye a los de esquina a:', 'options' => ['Calificar según sus puestos.', 'Calificar la fórmula completa.', 'Cambiar el orden de evaluación (A por B).', 'Puntuar nuevamente.'], 'correct' => 1, 'why' => 'En desempate los tres jueces evalúan la fórmula completa (no su asignación) y apuntan al mejor.'],
                ['q' => 'Una vez determinada la categoría de armas, el Central debe:', 'options' => ['Preguntar quiénes participarán en armas.', 'Verificar que las armas sean las oficiales.', 'Comenzar la categoría inmediatamente.', 'Todas las anteriores.'], 'correct' => 1, 'flag' => true, 'why' => "La inspección de armas (verificar que sean oficiales) es clave y va antes de comenzar. 'Comenzar inmediatamente' contradice la inspección."],
                ['q' => '¿Cuál de las siguientes acciones está permitida?', 'options' => ['Enrollar mangas a la altura del codo.', 'El cinturón puede guardarse siguiendo su línea.', 'Enrollar mangas a la altura del antebrazo.', 'Ninguna.'], 'correct' => 1, 'flag' => true, 'why' => 'El cinturón puede acomodarse siguiendo su línea.'],
                ['q' => 'Si un competidor en Xtreme Formula se pasa del tiempo:', 'options' => ['Se rebaja el puntaje.', 'El central otorga 0 y los de esquina puntúan normal.', 'No ajustar por tiempo sino por movimientos.', 'No recibe puntaje por pasarse.'], 'correct' => 1, 'why' => 'Hoy: el Central da 0 y los de esquina puntúan normal (sin descalificación).'],
                ['q' => 'En Tigers en Chile, indique la alternativa INCORRECTA:', 'options' => ['En fórmula muestran pulgares arriba y el central felicita.', 'En armas puede hacer fórmula libre de 30 seg.', 'En sparring se marca alternadamente rojo/blanco para empatar y ambos ganan.', 'En CW arbitran normal pero el marcador queda en cero y ambos ganan.', 'Se le da medalla por fórmula-Sparring y otra por cada extra.'], 'correct' => 2, 'flag' => true, 'why' => 'Falsa: el sparring de Tigers no se puntúa. Detalles de Chile.'],
                ['q' => 'La principal consideración al evaluar armas debe ser:', 'options' => ['Presentación del material y manejo por ambos lados.', 'Calidad de las patadas.', 'Tiempo y fluidez del arma.', 'A y C.'], 'correct' => 3, 'why' => 'Presentación/manejo + tiempo-fluidez; el control del arma es el criterio rector.'],
                ['q' => 'Si el arma se cae:', 'options' => ['El Central baja en negros e ignora en color.', 'Se detiene y se comienza de nuevo.', 'Todos los jueces bajan 1 pt por cada caída.', 'Se evalúa con 9.1 en negros.'], 'correct' => 2, 'why' => 'Todos los jueces descuentan 1 punto por cada caída.'],
                ['q' => 'El rol principal del Juez Central es:', 'options' => ['Determinar un ganador.', 'Cuidar la integridad de todos.', 'Determinar puntos claros.', 'Dejar contento al público.'], 'correct' => 1, 'why' => 'La seguridad de los competidores es la prioridad.'],
                ['q' => 'Protectores para los competidores:', 'options' => ['Obligatorios para negros.', 'Opcionales para color.', 'Obligatorios para todos los cinturones.', 'A criterio del Central.'], 'correct' => 2, 'why' => 'Obligatorios para todos en sparring y combat weapons.'],
                ['q' => 'Antes de comenzar el sparring, el Central debe:', 'options' => ['Verificar protectores.', 'Explicar reglas de sparring.', 'Explicar qué esperan los jueces.', 'Todas.'], 'correct' => 3, 'why' => 'Verifica equipo y explica reglas y expectativas.'],
                ['q' => 'Un Juez puede cambiar el color de la bandera en el caso de:', 'options' => ['Que los otros apunten al otro competidor.', 'Apunta al rojo con la bandera blanca.', 'Cuando el público pifia.', 'Ninguna.'], 'correct' => 1, 'why' => 'Si apunta al competidor correcto con el color equivocado, puede corregir el color.'],
                ['q' => 'Si el Central no está de acuerdo con una llamada a punto de un Esquina:', 'options' => ['Puede obviar el llamado y continuar.', 'Detener el tiempo y reunir a los jueces para explicar que no fue claro.', 'Llamar a punto pero hacer presente su desacuerdo.', 'Ninguna.'], 'correct' => 1, 'why' => 'Se detiene el tiempo y se hace una discusión informativa; decide la mayoría (el Central no anula).'],
                ['q' => 'Si un Juez escucha un punto pero no lo ve, ¿qué marca?', 'options' => ['1 punto.', 'No punto.', 'Advertencia.', 'No visto.'], 'correct' => 3, 'why' => "Marca 'No visto' y queda fuera de esa votación."],
                ['q' => 'Si un competidor muestra actitudes poco deportivas, ¿qué acción se toma?', 'options' => ['Sancionarlo con advertencia.', 'Ignorarlo.', 'Hacer flexiones.', 'Descalificarlo sin advertencia.'], 'correct' => 0, 'why' => 'Advertencia por conducta antideportiva, a criterio del Central.'],
                ['q' => 'El Central llama a punto y se marcan: 2 rojos, 3 rojos y 1 rojo. ¿Qué se entrega?', 'options' => ['Cero puntos.', '3 puntos rojos.', '1 punto rojo.', '2 puntos rojos.'], 'correct' => 3, 'why' => 'Mayoría a rojo; la nota común más alta con mayoría (2 de 3 dieron 2+) es 2.'],
                ['q' => 'Al realizar el sorteo de sparring, el Juez Central debe:', 'options' => ['Evitar compañeros de escuela en el primer y segundo sorteo.', 'Encargar el sorteo a un Esquina.', 'Pasar a 2da vuelta a campeones mundial/panamericano/nacional si hay libres.', 'Ninguna.'], 'correct' => 2, 'flag' => true, 'why' => "Los libres (byes) se priorizan a campeones (mundial → distrito/panam → estatal). La regla de 'misma escuela' aplica a la primera ronda."],
                ['q' => 'El coaching (entrenador) se permite en una categoría solo en:', 'options' => ['Tiny tigers.', 'Taekwondo for Kids.', 'Campeones Nacionales.', 'Team Sparring / CW.'], 'correct' => 3, 'why' => 'El coaching solo se permite en sparring/combat weapons por equipos.'],
                ['q' => 'Indique la alternativa que está correcta:', 'options' => ['Si son 3 competidores, salen los tres a presentar y luego se colocan las notas.', 'En Creative se permite lanzar el arma.', 'En Xtreme se descuenta 1 pt si pasa de 2 min.', 'En armas se descuenta 1 pt si rompe y consigue otra en 30 seg.', 'Con 3 en fórmula, el 2do siempre obtiene 8-8-8.'], 'correct' => 0, 'flag' => true, 'why' => 'Correcta la (a). La (e) puede ser válida en el sistema antiguo.'],
            ],
            4 => [
                ['q' => '¿Cuál es el objetivo de la evaluación en la competencia de fórmulas?', 'options' => ['Evaluar la técnica universal considerando diferencias por escuela/región.', 'Evaluar habilidad en la ejecución de técnicas.', 'Evaluar coordinación, concentración y fuerza.', 'B y C.', 'A, B y C.'], 'correct' => 4, 'why' => 'El objetivo abarca los tres: técnica universal, habilidad de ejecución y atributos (coordinación, concentración, fuerza).'],
                ['q' => 'Como Juez A, ¿qué criterio es el más importante en su evaluación?', 'options' => ['Altura de las patadas.', 'Técnica de sus patadas.', 'Estabilidad.', 'Fuerza.'], 'correct' => 1, 'flag' => true, 'why' => 'El Juez A evalúa posturas y patadas; la calidad de la técnica es lo central. La altura debe calzar con el cuerpo, no es el criterio rector.'],
                ['q' => "'El juez de esquina evalúa solo lo presentado y no juzga pasos omitidos.'", 'options' => ['Verdadero', 'Falso'], 'correct' => 0, 'why' => 'Correcto: los jueces de esquina solo puntúan las técnicas mostradas; las omisiones las evalúa el Central.'],
                ['q' => "'Un Juez B descontará puntos si el competidor hizo golpe de nudillo en vez de canto.'", 'options' => ['Verdadero', 'Falso'], 'correct' => 1, 'why' => 'Falso: una técnica incorrecta la evalúa el Central, no el juez de esquina.'],
                ['q' => 'Un Juez A descontará puntos por patear con la pierna equivocada.', 'options' => ['Verdadero', 'Falso'], 'correct' => 1, 'why' => 'Falso: el de esquina solo juzga la técnica mostrada; ese tipo de error lo maneja el Central.'],
                ['q' => "'Si el Central le pide subir o bajar una nota, debe hacerlo porque tiene más experiencia.'", 'options' => ['Verdadero', 'Falso'], 'correct' => 1, 'why' => 'Falso: cada juez puntúa de forma independiente; el Central no puede cambiar la nota de un juez de esquina.'],
                ['q' => 'Indique qué evaluación NO está correcta:', 'options' => ['9.9 el mejor del grupo.', '9.8–9.6 mejor que el promedio.', '9.5 el promedio.', '9.4–9.1 debajo del promedio.', '9.0 fórmula incompleta, la colocan los tres jueces.'], 'correct' => 4, 'why' => 'Falsa: el 9.0 por incompleta lo coloca SOLO el Juez Central.'],
                ['q' => 'Fórmula incompleta — puntaje de los Jueces de esquina:', 'options' => ['9.0', '9.5', '9.0 ó 9.1', '9.1 a 9.9', '9.0 a 9.5'], 'correct' => 3, 'why' => 'Los de esquina puntúan normal (9.1–9.9); solo el Central pone 0/9.0.'],
                ['q' => '¿Cuántas oportunidades para hacer la fórmula hay?', 'options' => ['1 vez para todos los grados.', '2 para Negros con autorización.', '1 leadership y 1 Negro.', '1 Negro y 2 Color.', '1 Negro (excepto infantil) y 2 Color.'], 'correct' => 0, 'why' => 'Una sola oportunidad para todos; no se repite en ninguna categoría.'],
                ['q' => 'En sparring y combat weapon, indique la alternativa correcta:', 'options' => ['El perímetro negro/rojo no tiene relevancia para los puntos.', 'Los puntos en la cabeza con salto valen 2 puntos.', 'Si se llama TIEMPO antes de contacto en la pechera, el punto NO es válido.', 'Si se llama TIEMPO antes de contacto en el cabezal, el punto es válido.'], 'correct' => 3, 'flag' => true, 'why' => 'No se exige contacto para puntuar si la técnica llegó controlada al blanco legal. (Cabeza con salto valen 3, no 2.)'],
                ['q' => "¿Qué se entiende por 'Victoria Súbita'?", 'options' => ['Ganar dentro del tiempo reglamentario.', 'El competidor se lesiona y no continúa.', 'Ganar en un combate extra de 1 minuto.', 'Ganar después de un empate, en un tiempo extra.', 'B y C.'], 'correct' => 3, 'why' => 'Tras un empate, en tiempo extra el primer punto gana (sin límite de tiempo).'],
                ['q' => 'Durante un sparring, ¿en qué momento los Jueces de esquina dan sus puntajes?', 'options' => ['En cualquier momento.', 'Cuando el combate está detenido y el Central lo pide.', 'Cuando ven puntos y detienen el combate sin esperar al Central.', 'Cuando ven mala intención.', 'En cualquier momento tras llamar a punto.'], 'correct' => 1, 'why' => 'Votan simultáneamente cuando el Central detiene el combate y pide la verificación.'],
                ['q' => '¿Cuáles son las áreas de evaluación de los Jueces de esquina en fórmula?', 'options' => ['Juez A: Piernas / patadas y posiciones.', 'Juez B: Piernas / patadas y posiciones.', 'Juez A: Memoria y fluidez.', 'Juez A y B evalúan como Central.', 'Juez A: Brazos / básicos.'], 'correct' => 0, 'why' => 'Juez A = posturas y patadas (piernas); Juez B = técnicas de mano y bloqueos (brazos).'],
                ['q' => 'Si el competidor está solo en una modalidad, ¿qué puntaje le pone el Juez de esquina?', 'options' => ['9.5 por no tener media comparativa.', '9.9 como mejor de su grupo.', 'No recibe puntaje; se apunta 1er lugar.', '9.1 por ser el único.', 'La nota que el juez estime conveniente.'], 'correct' => 1, 'why' => 'El único competidor recibe 9,9,9 por ser el mejor de su grupo ese día (salvo deducción automática, como incompleta).'],
                ['q' => 'Sobre la gesticulación de Punto / No punto / No visto / Advertencia, ¿cuál alternativa es correcta? (a) Punto: apunto con el banderín del color del competidor y con la otra mano la cantidad de puntos; No punto: cruzo las manos empuñadas en X en zona baja. (b) Punto: apunto el banderín hacia arriba y con la otra mano la cantidad; No punto: manos en X abajo. (c) No visto: cruzo las manos abiertas a la altura de la cara. (d) No visto: el juez se da media vuelta. (e) Advertencia: círculo con el banderín al suelo; Penalidad: banderín al suelo sin círculo. (f) Penalidad: círculo al suelo; Advertencia: banderín al suelo sin círculo.', 'options' => ['A, D y E son correctas.', 'B, C y F son correctas.', 'A, C y E son correctas.'], 'correct' => 2, 'why' => 'Son correctas la a (punto: banderín al competidor + dedos; no punto: brazos en X abajo), la c (no visto: manos a la altura de la cara) y la e (advertencia: banderín en círculo al suelo). La b es falsa (el banderín apunta al competidor); la d es falsa (no se da media vuelta); la f invierte advertencia y penalidad.'],
                ['q' => 'Indique la alternativa CORRECTA en sparring:', 'options' => ['Permitido puño a la cara si no hay mala intención.', 'Solo patadas sin giro a zona alta; a zona media, con y sin salto.', 'Técnica de puños a zona media.', 'Técnicas en zona baja permitidas 1 vez.'], 'correct' => 2, 'why' => 'Los puños solo son legales al torso frontal (zona media).'],
                ['q' => '¿Cuál es la puntuación por zona en sparring?', 'options' => ['1 pt: puño a la cara, puño medio, patada sin salto a la pechera.', '2 pts: puño con salto, patada con salto a pechera, patada a cabeza sin salto.', '1 pt: patada con salto a la pechera, puño medio.', '3 pts: patada con salto y giro a pechera.', '2 pts: patada con salto a la pechera, patada a la cabeza sin salto.', '1 pt: puño a la pechera, patada con salto a la pechera.'], 'correct' => 4, 'why' => 'Patada con salto al cuerpo = 2 y patada a la cabeza sin salto = 2. (Puño a la cara es ilegal.)'],
                ['q' => '¿En qué situación se permite una técnica de puño a la cara?', 'options' => ['Cuando tiene protector bucal.', 'Cuando no hay mala intención.', 'Los puños están permitidos en zona alta.', 'En ningún caso.'], 'correct' => 3, 'why' => 'Ninguna técnica de mano a la cabeza/cara es legal.'],
                ['q' => 'Áreas o técnicas ILEGALES para punto en sparring:', 'options' => ['Zona baja, puño a la cara, patada en la cabeza.', 'Puño medio, puño a la cara, patada en la espalda.', 'Patada a la cabeza, patada con giro a pechera, patada con salto a la cabeza.', 'Golpes en la espalda, puño a la cara, cualquier técnica zona baja, cuello.'], 'correct' => 3, 'why' => 'Ilegales: espalda, mano a la cara, todo bajo el cinturón y el cuello. (Patada a la cabeza SÍ es legal.)'],
                ['q' => 'Consideraciones sobre el llamado de advertencias:', 'options' => ['El tiempo sigue corriendo; advertencia y luego punto; puede recibir ambos.', 'El tiempo se detiene; advertencia y luego punto; puede recibir ambos.', 'El tiempo se detiene; punto y luego advertencia; no puede recibir ambos.', 'Si recibe advertencia puede recibir un punto a favor.', 'La 2da advertencia sin contacto descuenta 1 pt a su propio marcador.', 'La 1ra advertencia sin contacto da +1 al oponente.', 'El tiempo se detiene; advertencia y luego punto; NO puede recibir advertencia y punto a la vez.'], 'correct' => 6, 'why' => 'Se detiene el tiempo, se resuelve primero la advertencia y luego el punto; nunca advertencia y punto por la misma acción.'],
                ['q' => 'Sobre el perímetro durante el sparring:', 'options' => ['Por cada salida, una penalidad.', 'Correr fuera para evitar el combate está permitido.', 'El de afuera no puede hacer puntos ni recibirlos.', 'El de adentro marca al de afuera y está obligado a dejarlo entrar.', 'El de adentro puede golpear con salto si el punto ocurre antes de tocar el suelo fuera.'], 'correct' => 4, 'why' => 'Vale el punto con salto iniciado dentro si ocurre en el aire, antes de tocar fuera. (El de afuera SÍ puede recibir puntos; no hay obligación de dejarlo entrar; 2 salidas sin penalidad.)'],
                ['q' => 'Puntuación por zona en Combat Weapons:', 'options' => ['1 pt zonas legales: pierna, brazo, torso, espalda, estocada a la cara.', '1 pt: mano que sostiene el arma y estocada a la pierna delantera.', '2 pts: estocada pierna delantera, antebrazo y mano que sostiene arma, cabeza.', '3 pts: zona alta.', '3 pts: zona media con salto.', '2 pts: estocada a la cara y pierna delantera.', '1 pt: estocada a la cara.'], 'correct' => 2, 'why' => 'Valen 2: cabeza, brazo armado bajo el codo y estocada al muslo (pierna) delantero. Cuerpo = 1, +1 con salto, −1 por caída del arma.'],
                ['q' => '¿Qué zonas/técnicas son ILEGALES en Combat Weapons?', 'options' => ['Piernas, espalda, cabeza.', 'Estocada zona media, golpe al cuello.', 'Estocada pierna delantera, golpe a cabeza con salto, golpe en manos.', 'Estocada a la cara/ojos, zona genital y cuello.', 'Golpes con salto.', 'Solo golpes en la espalda.'], 'correct' => 3, 'why' => 'Ilegales: ingle, estocada a los ojos/cara y el cuello no cubierto por el casco.'],
                ['q' => '¿En qué casos se descuenta en una presentación de armas tradicional?', 'options' => ['Por caída del arma previo a la presentación.', 'Por dejar caer, recoger mal y olvidar 1–2 pasos.', 'Por romperse el arma.', 'Por incompleta, todos los jueces 9.0.', 'Incompleta: solo el Central 9.0; caída −1 de todos; mala recogida −1 de todos.', 'Solo por caída durante la presentación.'], 'correct' => 4, 'why' => 'Incompleta = 0 solo del Central. Caída = −1 de cada juez. Recoger mal (sin rodilla al suelo y ambas manos) = −1 de cada juez.'],
                ['q' => '¿Cuál corresponde a una advertencia de CONTACTO?', 'options' => ['Coaching, salidas reiteradas, patada zona baja.', 'Puño a la cara, patada zona baja, patada en el brazo.', 'Salidas reiteradas.', 'Dejarse caer.', 'Punto con el pie de apoyo fuera del perímetro.', 'Salto y giro a zona alta, golpe genital, golpe en espalda, puño a la cara.', 'Técnicas en la espalda, mano a la cara, golpe bajo el cinturón.'], 'correct' => 6, 'why' => 'Contacto = golpe ilegal que impacta: espalda, mano a la cara, bajo el cinturón. (Coaching, salidas, dejarse caer son SIN contacto.)'],
                ['q' => '¿Cuál corresponde a una advertencia de NO contacto?', 'options' => ['Coaching y salidas reiteradas.', 'Puño a la cara, dejarse caer, hacer tiempo, recibir instrucciones.', 'Salidas reiteradas, dejarse caer, hacer tiempo, recibir instrucciones.', 'Dejarse caer.', 'Punto con pie de apoyo fuera.', 'Hacer tiempo.', 'Regresar lento al llamado.'], 'correct' => 2, 'why' => 'Sin contacto: salidas reiteradas, dejarse caer, hacer tiempo y recibir coaching. (Puño a la cara es de contacto.)'],
                ['q' => 'Golpe de puño a la cara es penalidad y otorga un punto al oponente.', 'options' => ['Verdadero', 'Falso'], 'correct' => 0, 'why' => 'Verdadero: es contacto ilegal → +1 al rival (1ra infracción).'],
                ['q' => 'Golpe en zona baja se indica como advertencia sin penalización de puntos.', 'options' => ['Verdadero', 'Falso'], 'correct' => 1, 'why' => 'Falso: un golpe (contacto) en zona ilegal da +1 al oponente.'],
                ['q' => 'En sparring, un golpe en la espalda o el cuello no están permitidos.', 'options' => ['Verdadero', 'Falso'], 'correct' => 0, 'why' => 'Verdadero: la espalda y el cuello son zonas ilegales.'],
                ['q' => 'Exceso de contacto descalifica inmediatamente a un competidor.', 'options' => ['Verdadero', 'Falso'], 'correct' => 1, 'why' => 'Falso: queda a criterio del Central (puede ser punto o descalificación); solo la malicia descalifica de inmediato.'],
                ['q' => "Si el Central indica advertencia y los de esquina cobran 'no advertencia', prima el Central.", 'options' => ['Verdadero', 'Falso'], 'correct' => 1, 'why' => 'Falso: decide la mayoría; el voto del Central vale igual que el de los demás.'],
                ['q' => 'Recibir coaching/indicaciones se penaliza con 1 pt en el primer llamado.', 'options' => ['Verdadero', 'Falso'], 'correct' => 1, 'why' => 'Falso: la 1ra advertencia sin contacto es solo verbal; desde la 2da da +1 al rival.'],
                ['q' => 'Golpe de puño a la cara está permitido 1 vez sin ser penalizado.', 'options' => ['Verdadero', 'Falso'], 'correct' => 1, 'why' => 'Falso: nunca se permite; es advertencia de contacto (+1 al rival).'],
                ['q' => 'Indique la alternativa que está correcta:', 'options' => ['Juez B con 3 competidores: salen los tres y apunta con criterio como Juez Central por el 1er lugar.', 'En Creative Weapons se permite lanzar el arma.', 'En Xtreme se descuenta 1 pt de los tres jueces si pasa de 2 min.', 'En armas se descuenta 1 pt si rompe y consigue otra en 30 seg.', 'Con 3 competidores en fórmula tradicional, el 2do lugar obtiene 8-8-8.'], 'correct' => 4, 'why' => "Correcta la (e): con 2–3 competidores se apunta 1°=9, 2°=8, 3°=7 por juez. La (a) es falsa porque el Juez B apunta según su rol, no 'como Central'."],
                ['q' => "En 'fórmula de armas' (armas tradicionales), indique la alternativa correcta:", 'options' => ['Juez A: posiciones y patadas; Juez B: movimientos y control del arma.', 'Juez A: movimientos y control del arma; Juez B: posiciones y patadas.', 'Juez A y B evalúan la actuación completa (general), igual que el Central.'], 'correct' => 2, 'flag' => true, 'why' => 'En armas tradicionales (2025-26) todos los jueces evalúan la ejecución completa; solo el Central considera si está incompleta.'],
            ],
        ];
    }
}
